### ISSUE TITLE
Add a repo description

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/jenkins-libs#8]
We’re trying to make sure every repo has a description (see ipfs/docs#55) and this repo is missing one. I don’t have permissions to add it, but I’d suggest something like:

> 🚚 Framework for configuring tests to run on Jenkins

(Adding the truck so this also matches up with ipfs/docs#57)

**Comment by VictorBjelkholm** [comment]
Moved to https://github.com/ipfs/testing/issues/67
